/**
 * Regression: a realistic Phase 1 (schemaVersion 1) backup — generated by the
 * Phase 1 code itself (commit d8d0747) after ~5 weeks of simulated use, with
 * renamed / added / deleted topics and a custom category — must survive the
 * v1 → v2 migration byte-for-byte, via both upgrade paths.
 */
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import fixture from "@/test/fixtures/phase1-sample.json";
import { DexieRepository } from "@/lib/db/dexie-repository";
import { DB_NAME, HenyuDB } from "@/lib/db/schema";
import { SUBJECT_TEMPLATES, UNIVERSITY_TEMPLATES } from "@/lib/db/seed";
import { buildStudyModel } from "@/lib/model/buildStudyModel";
import type { BackupFile } from "@/lib/types";

const v1 = fixture as unknown as BackupFile;

let db: HenyuDB;
let repo: DexieRepository;

function deleteDb(): Promise<void> {
  return new Promise((resolve, reject) => {
    const req = indexedDB.deleteDatabase(DB_NAME);
    req.onsuccess = () => resolve();
    req.onblocked = () => resolve();
    req.onerror = () => reject(req.error);
  });
}

beforeEach(async () => {
  await deleteDb();
  db = new HenyuDB();
  repo = new DexieRepository(db);
});
afterEach(() => repo.close());

/** Fields migration is allowed to *add* to pre-existing rows. */
const ADDED: Record<string, string[]> = {
  subjects: ["evaluationType"],
  topics: ["dependsOn"],
};

function strip(row: object, table: string): Record<string, unknown> {
  const copy: Record<string, unknown> = { ...row };
  for (const f of ADDED[table] ?? []) delete copy[f];
  return copy;
}

async function expectPhase1DataIntact() {
  const tables = [
    "subjects",
    "categories",
    "topics",
    "studySessions",
    "reviews",
    "dailyGoals",
    "examScores",
  ] as const;
  for (const table of tables) {
    const original = v1.data[table] as { id: string }[];
    for (const row of original) {
      const stored = await db.table(table).get(row.id);
      expect(stored, `${table}/${row.id} missing`).toBeDefined();
      expect(strip(stored, table), `${table}/${row.id} changed`).toEqual(row);
    }
  }
  // activity history is only appended to
  for (const log of v1.data.activityLogs) {
    expect(await db.activityLogs.get(log.id)).toEqual(log);
  }
  // user settings survive; v2 fields are added
  const s = await repo.getSettings();
  const s1 = v1.data.settings[0]!;
  expect(s.examDate).toBe(s1.examDate);
  expect(s.examName).toBe(s1.examName);
  expect(s.autoLowerStatusOnFailedReview).toBe(s1.autoLowerStatusOnFailedReview);
  expect(s.dailyStudyGoalMin).toBe(s1.dailyStudyGoalMin);
  expect(s.onboardedAt).toBe(s1.onboardedAt);
  expect(s.primarySubjectId).toBe(s1.primarySubjectId);
  expect(s.schemaVersion).toBe(2);
}

async function expectV2Additions() {
  const subjects = await repo.listSubjects();
  expect(subjects).toHaveLength(SUBJECT_TEMPLATES.length);
  expect(subjects.filter((s) => s.slug === "math")).toHaveLength(1);
  expect(subjects.filter((s) => s.name === "数学")).toHaveLength(1);

  // math is exactly the user's math — no template topics re-added
  const mathCats = (await repo.listCategories("subj_math")).map((c) => c.id);
  const mathTopics = (await repo.listTopics()).filter((t) => mathCats.includes(t.categoryId));
  expect(mathTopics).toHaveLength(v1.data.topics.length);
  const names = mathTopics.map((t) => t.name);
  expect(names).not.toContain("三重積分"); // deleted by the user in Phase 1
  expect(names).not.toContain("グラフ"); // renamed by the user
  expect(names).toContain("グラフの平行移動");
  expect(names).toContain("絶対値");
  expect(names).toContain("期待値");

  expect(await db.universities.count()).toBe(UNIVERSITY_TEMPLATES.length);
  expect((await db.universities.get("univ_uec"))?.examDate).toBe("2027-07-10");
  const past = await db.pastExams.toArray();
  expect(past.map((p) => p.score).sort()).toEqual([48, 61]);
  expect(past.every((p) => p.universityId === "univ_uec")).toBe(true);

  const model = buildStudyModel(await repo.getSnapshot());
  const math = model.subjectSummaries.find((s) => s.subject.id === "subj_math");
  expect(math?.topicCount).toBe(v1.data.topics.length);
  expect(model.snapshot.sessions).toHaveLength(v1.data.studySessions.length);
}

async function expectIdempotent() {
  const before = await repo.exportBackup();
  expect(await repo.initialize()).toEqual({ seeded: false, migrated: false });
  expect((await repo.ensureExamTemplate()).addedSubjects).toEqual([]);
  const after = await repo.exportBackup();
  expect({ ...after.data, activityLogs: [] }).toEqual({ ...before.data, activityLogs: [] });
}

describe("Phase 1 → Phase 2 migration with a real Phase 1 backup", () => {
  it("fixture is a genuine schemaVersion 1 export", () => {
    expect(v1.schemaVersion).toBe(1);
    expect(v1.data.subjects).toHaveLength(1);
    expect(v1.data.topics.length).toBeGreaterThan(90);
  });

  it("in-place upgrade (existing IndexedDB opened by the v2 app)", async () => {
    // lay the v1 rows down exactly as the Phase 1 app stored them
    const d = v1.data;
    await db.subjects.bulkAdd(d.subjects);
    await db.categories.bulkAdd(d.categories);
    await db.topics.bulkAdd(d.topics);
    await db.studySessions.bulkAdd(d.studySessions);
    await db.reviews.bulkAdd(d.reviews);
    await db.dailyGoals.bulkAdd(d.dailyGoals);
    await db.examScores.bulkAdd(d.examScores);
    await db.settings.bulkAdd(d.settings);
    await db.activityLogs.bulkAdd(d.activityLogs);

    expect(await repo.initialize()).toEqual({ seeded: false, migrated: true });
    await expectPhase1DataIntact();
    await expectV2Additions();
    await expectIdempotent();
  });

  it("JSON import of the v1 backup into a v2 install", async () => {
    await repo.initialize(); // a fresh v2 install with template data
    await repo.importBackup(v1);
    await expectPhase1DataIntact();
    await expectV2Additions();
    await expectIdempotent();
  });

  it("v2 export → import round-trips the migrated data", async () => {
    await repo.importBackup(v1);
    const exported = await repo.exportBackup();
    await repo.resetAll();
    await repo.importBackup(exported);
    await expectPhase1DataIntact();
    await expectV2Additions();
  });

  it("refuses a backup from a newer app version without touching current data", async () => {
    await repo.importBackup(v1);
    const before = await repo.exportBackup();
    const future = { ...before, schemaVersion: 99, data: { ...before.data, topics: [] } };
    await expect(repo.importBackup(future as BackupFile)).rejects.toThrow(/新しいバージョン/);
    const after = await repo.exportBackup();
    expect(after.data).toEqual(before.data);
  });
});
